Mahasiswa/Mahasiswa/Models/Image.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;
namespace Mahasiswa.Models
{
    public class ImageTest
    {

    }

    public class Image
    {
        public int ImageID { get; set; }
        public string Title { get; set; }
        [DisplayName("Upload File")]
        public string ImagePath { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }

        public HttpPostedFileBase ImageFileEdit { get; set; }
    }
}

Mahasiswa/Mahasiswa/Controllers/ImageController.cs
using Mahasiswa.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;
using Mahasiswa.Services;

namespace Mahasiswa.Controllers
{
    public class ImageController : Controller
    {
        string mainConnection = WebConfigurationManager.ConnectionStrings["MahasiswaConnection"].ConnectionString;
        ImageServices imageservices = new ImageServices();
        // GET: Image
        [HttpGet]
        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(Image imageModel)
        {
            string fileName = Path.GetFileNameWithoutExtension(imageModel.ImageFile.FileName);
            string extension = Path.GetExtension(imageModel.ImageFile.FileName);
            fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
            imageModel.ImagePath = "~/Content/img/" + fileName;
            fileName = Path.Combine(Server.MapPath("~/Content/img/" + fileName));
            imageModel.ImageFile.SaveAs(fileName);

            ViewBag.image = imageservices.insertImage(imageModel);
            ModelState.Clear();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Index()
        {
            ViewBag.image = imageservices.getImage();
            return View();

        }

        [HttpGet]
        public ActionResult Details(int id)
        {
            ViewBag.detail = imageservices.detail(id);
            ViewBag.title = ViewBag.detail.Title;
            ViewBag.path = ViewBag.detail.ImagePath;
            return View();
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            ViewBag.edit = imageservices.detail(id);
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Image imageModel)
        {
            string fileEditName = Path.GetFileNameWithoutExtension(imageModel.ImageFileEdit.FileName);
            string extension = Path.GetExtension(imageModel.ImageFileEdit.FileName);
            fileEditName = fileEditName + DateTime.Now.ToString("yymmssfff") + extension;
            imageModel.ImagePath = "~/Content/img/" + fileEditName;
            fileEditName = Path.Combine(Server.MapPath("~/Content/img/" + fileEditName));
            imageModel.ImageFileEdit.SaveAs(fileEditName);

            ViewBag.edit = imageservices.edit(imageModel);
            ModelState.Clear();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            ViewBag.deleteDetail = imageservices.detail(id);
            ViewBag.id = ViewBag.deleteDetail.ImageID;
            ViewBag.title = ViewBag.deleteDetail.Title;
            ViewBag.path = ViewBag.deleteDetail.ImagePath;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(Image imageModel, int id)
        {
            ViewBag.delete = imageservices.delete(imageModel, id);
            return RedirectToAction("Index");
        }
    }
}

Mahasiswa/Mahasiswa/Views/Image/Add.cshtml
@model Mahasiswa.Models.Image


@using (Html.BeginForm("Add","Image", FormMethod.Post, new {enctype = "multipart/form-data"} )) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Image</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImagePath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
               <input type="file" name="ImageFile" required />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Mahasiswa/Mahasiswa/Views/Image/Delete.cshtml
@model Mahasiswa.Models.Image

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Image</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @ViewBag.title
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImagePath)
        </dt>

        <dd>
            <img src="@Url.Content(ViewBag.path)" width="250" height="250" />
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Mahasiswa/Mahasiswa/Views/Image/Details.cshtml
@model Mahasiswa.Models.Image

<div>
    <h4>Detail Image</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @ViewBag.title
        </dd>

        <dt>
          <label>Uploaded File</label> 
        </dt>

        <dd>
            <img src="@Url.Content(ViewBag.path)" width="250" height="250" />
        </dd>

    </dl>
</div>
<p>
    @*@@Html.ActionLink("Edit", "Edit", new { id = Model.ImageID }) *@ |
    @Html.ActionLink("Back to List", "Index")
</p>

Mahasiswa/Mahasiswa/Views/Image/Edit.cshtml
@model Mahasiswa.Models.Image
@using Mahasiswa.Models
@{ 
    Image edit = ViewBag.edit;
}

@using (Html.BeginForm("Edit", "Image", FormMethod.Post, new {enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Update Image</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ImageID, new {@Value = edit.ImageID, @id =  "id"})

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new {@Value = edit.Title ,@class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImagePath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="ImageFileEdit" required />

                @* @Html.EditorFor(model => model.ImagePath, new { htmlAttributes = new { @Value = edit, @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.ImagePath, "", new { @class = "text-danger" })*@
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Mahasiswa/Mahasiswa/Views/Image/Index.cshtml
@model Mahasiswa.Models.Image
@using Mahasiswa.Models
@{
    List<Image> image = ViewBag.image;
}

    <a href="~/Image/Add" class="btn btn-success mt-5">Upload Gambar</a>


<table class="table table-striped table-bordered">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ImageID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ImagePath)
        </th>
        <th></th>
    </tr>

    @foreach (var item in image)
    {
        <tr>
            <td>@Html.DisplayFor(modelItem => item.ImageID)</td>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                <img src="@Url.Content(item.ImagePath)" width="250" height="250" />
            </td>
            <td align="center">
                <a href="~/Image/Edit?id=@item.ImageID" class="btn btn-warning mr-2">Edit</a>
                <a href="~/Image/Details?id=@item.ImageID" class="btn btn-info mr2">Details</a>
                <a href="~/Image/Delete?id=@item.ImageID" class="btn btn-danger">Delete</a>

            </td>
        </tr>
    }

</table>